---
# role: ansible-role-ubuntu-clean
# file: tasks/tasks.yml

- name: Set os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'
  ignore_errors: True

- name: Set distribution dependent variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: True
  loop_control:
    loop_var: vars_file

- name: Install packages for ansible-role-ubuntu-clean
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ ubuntu_clean_packages_install }}"

- name: Uninstall unwanted packages
  apt:
    name: "{{ item }}"
    state: absent
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
    purge: yes
  loop: "{{ ubuntu_clean_packages_remove }}"
