---
# role: ansible-role-ubuntu-clean
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 4096
      cpus: 2
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ubuntu-clean-ubuntu1604
    box: "generic/ubuntu1604"
  - name: ubuntu-clean-ubuntu1804
    box: "generic/ubuntu1804"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_ubuntu-clean_enabled: True
scenario:
  name: kvm
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
