---
# role: ansible-role-ubuntu-clean
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: ubuntu-clean-default
    image: ${MOLECULE_DIST:-"jam82/ubuntu-molecule:18.04"}
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    tty: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        role_ubuntu-clean_enabled: True
scenario:
  name: podman
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
